### ISSUE TITLE
TODO Brainstorm

### ISSUE THREAD

**Issue by xackery** [daeken/OpenEQ#61]
* [ ] Implement netcode.
* [ ] Design CI testing suite
* [ ] Add physics
* [ ] Isolate and resolve model import errors.
* [ ] Add alpha text support
* [ ] Add classic character model support
* [ ] Add luclin character model support
* [ ] Clean up the program start workflow, ideally adding command arguments for quick loading certain test use cases
* [ ] Get an artist to pack opensource model assets for  s3d/eqg etc that tests can use to verify integrity of code (this should be on the repo, with no copyright concerns)
* [ ] Create a demo zone
* [ ] Publish a release demo using demo zone and assets to show others the progress of the project without having to compile from scratch
* [ ] Extend demo above to also load EQ Directory eqg/s3d for demoing the project with EQ assets
* [ ] Create initial GUI version
* [ ] Implement prototype model pooling
* [ ] Add Particle Effects system
* [ ] Add command line system to issue various commands, mirroring EQ commands to start (e.g. /zone, /goto, etc)
* [ ] Idea: Add an On-The-Fly zone loader, seeing if a conversion cache exists, and if not, build it during a zone load?
